### ISSUE TITLE
JSON Lock File "in future" prevents a start

### ISSUE THREAD

**Issue by Apollon77** [AlCalzone/jsonl-db#370]
Sometimes with raspis or such on a hart restart the time resets to an earlier timepoint because of fakehwclock.

See https://forum.iobroker.net/post/851675 ... In this case it seems that the used lockfile library do not consider such files as stale and so it considers the logfile as valid and prevents the start.

**Comment by AlCalzone** [comment]
fixed in 2.5.3, building now
